import type { Metadata } from "next";
import { Roboto, JetBrains_Mono as JetBrainsMono } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"]
});

const jetbrainsMono = JetBrainsMono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${jetbrainsMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
